{% set name = "h3" %}
{% set version = "3.7.6" %}

package:
  name: {{ name|lower }}-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9bbd3dbac99532fa521d7d2e288ff55877bea3223b070f659ed7b5f8f1f213eb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make                  # [unix]
  host:
    - python
    # scikit-build runs cmake in host
    - cmake
    - cython
    - pip
    - scikit-build
    - setuptools
    - wheel
  run:
    - python
    # To enable an optional numpy_int API, see https://github.com/uber/h3-py/blob/f3f0144c76c60bb4fe50ca9e5d210290a2824a94/src/h3/api/numpy_int/_binding.py#L6-L7
    - numpy

test:
  imports:
    - h3
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/uber/h3-py
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Uber's H3 Hexagonal Hierarchical Geospatial Indexing System in Python
  description: |
    Uber's H3 Hexagonal Hierarchical Geospatial Indexing System in Python
  doc_url: https://uber.github.io/h3-py/intro.html
  dev_url: https://github.com/uber/h3-py

extra:
  recipe-maintainers:
    - mxr-conda
    - bubblyorca
    - geoHeil
