{% set name = "h3" %}
{% set version = "3.6.2" %}

package:
  name: {{ name|lower }}-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ca52df4e9bc3007720f3fd34478549853dc5ab17c24ed23b3b3c05bac511b8b8

build:
  number: 0
  skip: true  # [python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - scikit-build
    - cython
  run:
    - python
    - numpy

test:
  imports:
    - h3

about:
  home: https://github.com/uber/h3-py.git
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python bindings for H3, a hierarchical hexagonal geospatial indexing system developed by Uber Technologies
  dev_url: https://github.com/uber/h3-py.git

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - geoHeil
